config/routes.rb
Rails.application.routes.draw do
  devise_for :people
  root 'top#index'

  resources :job_offers

  resources :circles do
    resources :job_offers do
      resources :messages
    end
  end

  namespace :admin do
    get 'login' => ''
    get 'dashboard' => 'dashboard#index'
    resource  :organization, only: %i[show edit update]
    resources :users
    resources :circles do
      resources :members
    end
    resources :job_offers
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/circle.rb
# frozen_string_literal: true

class Circle < ApplicationRecord # :nodoc:
  has_and_belongs_to_many :members, class_name: 'Person', join_table: 'circles_people'
  belongs_to :parent,   class_name: 'Circle', foreign_key: 'circle_id', optional: true
  has_many   :children, class_name: 'Circle', foreign_key: 'circle_id'

  def parent_name
    parent.nil? ? '' : parent.name
  end
end

app/models/job_offer.rb
class JobOffer < ApplicationRecord
  belongs_to :circle

  enum status: {
    unpublished: 0,
    published:   1,
    closed:      9
  }

  enum job_type: {
    undefined:  0,
    engineer:  10,
    sales:     20
  }

  enum employment_type: {
    full_time:  0,
    part_time: 10
  }
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :people
end

app/models/person.rb
# frozen_string_literal: true

class Person < ApplicationRecord # :nodoc:
  has_and_belongs_to_many :circles
  belongs_to :organization, optional: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: {
    normal: 0,
    admin:  1
  }
end

app/controllers/admin/circles_controller.rb
class Admin::CirclesController < ApplicationController

  before_action :set_circle, only: [:edit, :update, :destroy]

  def index
    @circles = Circle.all
  end

  def new
    @circle = Circle.new do |o|
    end
  end

  def edit
  end

  def create
    @circle = Circle.new(circle_params)

    if @circle.save
      redirect_to admin_circles_path, flash: { success: 'success' }
    else
      flash[:error] = 'error'
      render :new
    end
  end

  def update
    @circle.members = Person.where(id: params[:circle][:person_ids].uniq) if params[:circle][:person_ids]
    @circle.parent  = Circle.find_by(name: params[:circle][:parent_name]) if params[:circle][:parent_name]
    @circle.name    = params[:circle][:name]                              if params[:circle][:name]
    if @circle.save
      redirect_to admin_circles_path, flash: { success: 'success' }
    else
      flash[:error] = 'error'
      render :edit
    end
  end

  def destroy
    if @circle.destroy
      redirect_back fallback_location: admin_circles_url, flash: { success: 'success' }
    else
      redirect_back fallback_location: admin_circles_url, flash: { success: 'error' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_circle
    @circle = Circle.find_by!(id: params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def circle_params
    params.require(:circle).permit(
      :name,
      :person_ids,
      :parent_name
    )
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def index
  end
end

app/controllers/admin/job_offers_controller.rb
class Admin::JobOffersController < ApplicationController

  before_action :set_job_offer, only: [:edit, :update, :destroy]

  def index
    @job_offers = JobOffer.all
  end

  def new
    @job_offer = JobOffer.new do |o|
      o.status = JobOffer.statuses[:unpublished]
      o.circle_id = 1
    end
  end

  def edit
  end

  def create
    @job_offer = JobOffer.new(job_offer_params)

    if @job_offer.save
      redirect_to admin_job_offers_path, flash: { success: 'success' }
    else
      flash[:error] = 'error'
      render :new
    end
  end

  def update
    if @job_offer.update(job_offer_params)
      redirect_to admin_job_offers_path, flash: { success: 'success' }
    else
      flash[:error] = 'error'
      render :edit
    end
  end

  def destroy
    if @job_offer.destroy
      redirect_back fallback_location: admin_job_offers_url, flash: { success: 'success' }
    else
      redirect_back fallback_location: admin_job_offers_url, flash: { success: 'error' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_offer
      @job_offer = JobOffer.find_by!(id: params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def job_offer_params
      params.require(:job_offer).permit(:title, :content, :circle_id, :status)
    end
end

app/controllers/admin/members_controller.rb
# frozen_string_literal: true

class AdminMembersController < ApplicationController # :nodoc:
  before_action :set_circle

  def index
    @organization = Organization.find(1)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_circle
    @circle = Circle.find_by!(id: params[:circle_id])
  end

  # Only allow a trusted parameter "white list" through.
  def member_params
    params.require(:person).permit(:name)
  end
end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < ApplicationController

  before_action :set_organization, only: [:show, :edit, :update]

  def show
  end

  def edit
  end

  def update
    if @organization.update(organization_params)
      redirect_to admin_organization_path, flash: { success: 'success' }
    else
      flash[:error] = 'error'
      render :edit
    end
  end

  private
    def set_organization
      @organization = Organization.all.first
    end

    def organization_params
      params.require(:organization).permit(:name)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = Person.all
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, flash: { success: 'success' }
    else
      flash[:error] = 'error'
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_back fallback_location: admin_users_url, flash: { success: 'success' }
    else
      redirect_back fallback_location: admin_users_url, flash: { success: 'error' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = Person.find_by!(id: params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:person).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_person!
end

app/controllers/circles_controller.rb
# frozen_string_literal: true

class CirclesController < NoAuthController # :nodoc:
  def index
    @circles = Circle.all
  end

  def show
    @circle = Circle.find(params[:id])
  end
end

app/controllers/job_offers_controller.rb
class JobOffersController < NoAuthController

  def index
    @job_offers = JobOffer.published
  end

  def show
    @job_offer = JobOffer.find(params[:id])
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController # :nodoc:

  def show
  end

end

app/controllers/no_auth_controller.rb
class NoAuthController < ApplicationController
  protect_from_forgery with: :exception
  skip_before_action :authenticate_person!
end

app/controllers/top_controller.rb
class TopController < NoAuthController
  def index
    render layout: nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/job_offers_helper.rb
module JobOffersHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/admin/circles/_form.slim
= form_for [:admin, @circle], html: { class: 'form-horizontal' } do |f|
  - if @circle.errors.any?
    .panel-body
      .alert.alert-danger
        ul.list-unstyled
          - @circle.errors.full_messages.each do |message|
            li = message

  .panel-body
    .form-group
      = f.label :name, class: 'control-label col-sm-2 required'
      .col-sm-10
        = f.text_field :name, class: 'form-control'
    .form-group
      = f.label :parent_name, class: 'control-label col-sm-2'
      .col-sm-10
        = f.text_field :parent_name, class: 'form-control'
  .panel-footer.text-center
    => f.submit "save", class: 'btn btn-primary'
    = link_to "back", admin_circles_path, class: 'btn btn-default'

app/views/admin/circles/edit.slim
.container
  .panel
    .panel-header
      h2 edit circle
    .panel-body
      == render 'form'

app/views/admin/circles/index.slim
.container.content-main

  .panel.panel-default
    .panel-header
      = link_to 'new', new_admin_circle_path, class: "btn btn-primary"
    .panel-body
      table.table.table-rspnsv.table-hover
        thead
          tr.row
            th.col-sm-1
              = t('activerecord.attributes.circle.name')
            th.col-sm-1
              = t('activerecord.attributes.circle.parent')
            th.col-sm-2
              = t('activerecord.attributes.circle.children')
            th.col-sm-4
              = t('activerecord.attributes.circle.members')
            th.col-sm-4
              = ''

        tbody
          - @circles.each do |circle|
            tr.row
              td.col-sm-1[aria-label="name"]  = circle.name
              td.col-sm-1[aria-label="name"]  = circle.parent_name
              td.col-sm-2[aria-label="name"]
                - circle.children.each do |child|
                  = child.name
                  br
              td.col-sm-4[aria-label="name"]
                .row
                  - circle.members.each do |member|
                    .col-sm-3 = member.name
              td.col-sm-4
                => link_to fa_icon('edit', text: 'edit'), edit_admin_circle_path(circle), class: 'btn btn-sm btn-primary'
                => link_to fa_icon('trash', text: 'destroy'), admin_circle_path(circle), class: 'btn btn-sm btn-danger', data: { confirm: 'are you sure?' }, method: :delete
                = link_to "member", admin_circle_members_path(circle.id), class: 'btn btn-sm btn-primary'

app/views/admin/circles/new.slim
.container
  .panel
    .panel-header
      h2 new circle
    .panel-body
      == render 'form'

app/views/admin/dashboard/index.slim
.container
  .panel
    .panel-header
      h2 Dashboard
    .panel-body
      span dashboard

app/views/admin/job_offers/_form.slim
= form_for [:admin, @job_offer], html: { class: 'form-horizontal' } do |f|
  - if @job_offer.errors.any?
    .panel-body
      .alert.alert-danger
        ul.list-unstyled
          - @job_offer.errors.full_messages.each do |message|
            li = message

  .panel-body
    .form-group
      = f.label :title, class: 'control-label col-sm-2 required'
      .col-sm-10
        = f.text_field :title, class: 'form-control'
    .form-group
      = f.label :content, class: 'control-label col-sm-2'
      .col-sm-10
        = f.text_area :content, :size => '20x10', class: 'form-control'
    .form-group
      = f.label :circle_id, class: 'control-label col-sm-2'
      .col-sm-10
        = f.text_field :circle_id, class: 'form-control'
    .form-group
      = f.label :status, class: 'control-label col-sm-2 required'
      .col-sm-10
        - JobOffer.statuses_i18n.invert.each do |state|
          label.radio-inline
            = f.radio_button :status, state[1], class: 'optradio'
            = state[0]
  .panel-footer.text-center
      => f.submit "save", class: 'btn btn-primary'
      = link_to "back", admin_job_offers_path, class: 'btn btn-default'

app/views/admin/job_offers/edit.slim
.container
  .panel
    .panel-header
      h2 new offer
    .panel-body
      == render 'form'

app/views/admin/job_offers/index.slim
.container.content-main

  .panel.panel-default
    .panel-header
      = link_to 'new', new_admin_job_offer_path, class: "btn btn-primary"
    .panel-body
      table.table.table-rspnsv.table-hover
        thead
          tr
            th[width="80px"] 
              = t('activerecord.attributes.job_offer.status')
            th
              = t('activerecord.attributes.job_offer.title')
            th[width="180px"] 
              = t('activerecord.attributes.job_offer.content')
            th[width="150px"] 
              = t('activerecord.attributes.job_offer.circle_id')

        tbody
          - @job_offers.each do |offer|
            tr
              td[aria-label="status"]  = offer.status_i18n
              td[aria-label="title"]   = offer.title
              td[aria-label="content"] = offer.content
              td[aria-label="circle"]  = offer.circle_id
              td
                => link_to fa_icon('edit', text: 'edit'), edit_admin_job_offer_path(offer), class: 'btn btn-sm btn-default'
                = link_to fa_icon('trash', text: 'destroy'), admin_job_offer_path(offer), class: 'btn btn-sm btn-default', data: { confirm: 'are you sure?' }, method: :delete

app/views/admin/job_offers/new.slim
.container
  .panel
    .panel-header
      h2 edit offer
    .panel-body
      == render 'form'

app/views/admin/organizations/_form.slim
= form_for @organization, url: admin_organization_path, html: { class: 'form-horizontal' } do |f|
  - if @organization.errors.any?
    .panel-body
      .alert.alert-danger
        ul.list-unstyled
          - @organization.errors.full_messages.each do |message|
            li = message

  .panel-body
    .form-group
      = f.label :name, class: 'control-label col-sm-2 required'
      .col-sm-10
        = f.text_field :name, class: 'form-control'
  .panel-footer.text-center
      => f.submit "save", class: 'btn btn-primary'
      = link_to "back", admin_organization_path, class: 'btn btn-default'

app/views/admin/organizations/edit.slim
.container.content-main
  .panel
    .panel-header
      h2 Edit Organization
    .panel-body
      == render 'form'

app/views/admin/organizations/show.slim
.container.content-main

  .panel.panel-default
    .panel-header
      h4 Organization Info.
    .panel-body
      table.table.table-rspnsv.table-hover
        thead
          tr
            th[width="150px"] name

        tbody
          tr
            td[aria-label="status"]  = @organization.name
        => link_to fa_icon('edit', text: 'edit'), edit_admin_organization_path(@organization), class: 'btn btn-sm btn-default'

app/views/admin/users/_form.slim
= form_for @user, url: admin_user_path, html: { class: 'form-horizontal' } do |f|
  - if @user.errors.any?
    .panel-body
      .alert.alert-danger
        ul.list-unstyled
          - @user.errors.full_messages.each do |message|
            li = message

  .panel-body
    .form-group
      = f.label :name, class: 'control-label col-sm-2 required'
      .col-sm-10
        = f.text_field :name, class: 'form-control'
  .panel-footer.text-center
      => f.submit "save", class: 'btn btn-primary'
      = link_to "back", admin_users_path, class: 'btn btn-default'

app/views/admin/users/edit.slim
.container
  .panel
    .panel-header
      h2 edit user
    .panel-body
      == render 'form'

app/views/admin/users/index.slim
.container.content-main

  .panel.panel-default
    .panel-header
    .panel-body
      table.table.table-rspnsv.table-hover
        thead
          tr
            th[width="150px"]
              = t('activerecord.attributes.user.name')

        tbody
          - @users.each do |user|
            tr
              td[aria-label="name"]  = user.name
              td
                => link_to fa_icon('edit', text: 'edit'), edit_admin_user_path(user), class: 'btn btn-sm btn-default'
                = link_to fa_icon('trash', text: 'destroy'), admin_user_path(user), class: 'btn btn-sm btn-default', data: { confirm: 'are you sure?' }, method: :delete

app/views/circles/index.slim
.container.content-main

  .panel.panel-default
    .panel-body
      table.table.table-rspnsv.table-hover
        thead
          tr
            th
              = t('activerecord.attributes.circle.name')
            th
              = ''

        tbody
          - @circles.each do |circle|
            tr
              td[aria-label="name"]  = circle.name
              td
                = link_to 'detail', circle_path(circle.id), class: 'btn btn-sm btn-primary'

app/views/circles/show.slim
.container.content-main
  .panel.panel-default
    .panel-header
      h4
        = @circle.name
    .panel-body

app/views/job_offers/_form.slim
= form_for @job_offer, html: { class: 'form-horizontal' } do |f|
  - if @job_offer.errors.any?
    .panel-body
      .alert.alert-danger
        ul.list-unstyled
          - @job_offer.errors.full_messages.each do |message|
            li = message

  .panel-body
    .form-group
      = f.label :title, class: 'control-label col-sm-2 required'
      .col-sm-10
        = f.text_field :title, class: 'form-control'
    .form-group
      = f.label :content, class: 'control-label col-sm-2'
      .col-sm-10
        = f.text_area :content, :size => '20x10', class: 'form-control'
    .form-group
      = f.label :circle_id, class: 'control-label col-sm-2'
      .col-sm-10
        = f.text_field :circle_id, class: 'form-control'
    .form-group
      = f.label :status, class: 'control-label col-sm-2 required'
      .col-sm-10
        - JobOffer.statuses_i18n.invert.each do |state|
          label.radio-inline
            = f.radio_button :status, state[1], class: 'optradio'
            = state[0]
  .panel-footer.text-center
      => f.submit "save", class: 'btn btn-primary'
      = link_to "back", job_offers_path, class: 'btn btn-default'

app/views/job_offers/_item.slim
.panel.panel-default
  .panel-header
    = link_to offer.title, circle_job_offer_path(offer.circle_id, offer.id)
    = offer.job_type_label
    = offer.employment_type
  .panel-body
    .
      = t('activerecord.attributes.job_offer.circle_id')
      = offer.circle.name
    .
      = offer.content
    .

app/views/job_offers/index.slim
.container.content-main
  - @job_offers.each do |offer|
    = render 'item', offer: offer

app/views/job_offers/show.slim
.container.content-main
  .panel.panel-default
    .panel-header
      h4
        = @job_offer.title
      span
        = @job_offer.job_type_label
        = @job_offer.employment_type
        - if current_person
          = link_to 'propose!', circle_job_offer_message_path(circle_id: @job_offer.circle_id,
                                                            job_offer_id: @job_offer.id),
                                                            class: 'btn btn-sm btn-info'
    .panel-body
      = @job_offer.content

app/views/messages/show.slim
.container.content-main
  .panel.panel-default
    .panel-header
    .panel-body

app/views/top/index.slim
= stylesheet_link_tag 'top'

h1 Distributed Recruitment SNS HR-Circle
.container
  .panel
    .panel-header
      h2.labeled-logo HR-Circle
    .panel-body
    = link_to 'search offers', job_offers_path, class: 'btn btn-primary'
  .panel
    .panel-header
      h3 About
    .panel-body
      div
        span
          | sample text. sample text. sample text. sample text. sample text.
          | sample text. sample text. sample text. sample text. sample text.
          | sample text. sample text. sample text. sample text. sample text.
          | sample text. sample text. sample text. sample text. sample text.
          | sample text. sample text. sample text. sample text. sample text.